/*
  Copyright (c) 2021, All partners of the iTesla project (http://www.itesla-project.eu/consortium)
  This Source Code Form is subject to the terms of the Mozilla Public
  License, v. 2.0. If a copy of the MPL was not distributed with this
  file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.gridsuite.modification;

/**
 * @author Slimane Amar <slimane.amar at rte-france.com>
 * @author Franck Lecuyer <franck.lecuyer at rte-france.com>
 */
public enum ModificationType {
    EQUIPMENT_ATTRIBUTE_MODIFICATION,
    LOAD_CREATION,
    LOAD_MODIFICATION,
    BALANCES_ADJUSTMENT_MODIFICATION,
    BATTERY_CREATION,
    BATTERY_MODIFICATION,
    GENERATOR_CREATION,
    GENERATOR_MODIFICATION,
    EQUIPMENT_DELETION,
    BY_FILTER_DELETION,
    LINE_CREATION,
    LINE_MODIFICATION,
    TWO_WINDINGS_TRANSFORMER_CREATION,
    TWO_WINDINGS_TRANSFORMER_MODIFICATION,
    GROOVY_SCRIPT,
    SUBSTATION_CREATION,
    SUBSTATION_MODIFICATION,
    SHUNT_COMPENSATOR_CREATION,
    SHUNT_COMPENSATOR_MODIFICATION,
    STATIC_VAR_COMPENSATOR_CREATION,
    VOLTAGE_LEVEL_CREATION,
    VOLTAGE_LEVEL_MODIFICATION,
    LINE_SPLIT_WITH_VOLTAGE_LEVEL,
    LINE_ATTACH_TO_VOLTAGE_LEVEL,
    LINES_ATTACH_TO_SPLIT_LINES,
    GENERATOR_SCALING,
    LOAD_SCALING,
    OPERATING_STATUS_MODIFICATION,
    DELETE_VOLTAGE_LEVEL_ON_LINE,
    DELETE_ATTACHING_LINE,
    GENERATION_DISPATCH,
    VOLTAGE_INIT_MODIFICATION,
    VSC_CREATION,
    VSC_MODIFICATION,
    CONVERTER_STATION_CREATION,
    CONVERTER_STATION_MODIFICATION,
    TABULAR_MODIFICATION,
    TABULAR_CREATION,
    BY_FORMULA_MODIFICATION,
    MODIFICATION_BY_ASSIGNMENT,
    COMPOSITE_MODIFICATION,
    LCC_CONVERTER_STATION_CREATION,
    LCC_CONVERTER_STATION_MODIFICATION,
    LCC_CREATION,
    LCC_MODIFICATION,
    VOLTAGE_LEVEL_TOPOLOGY_MODIFICATION,
    CREATE_COUPLING_DEVICE,
    CREATE_VOLTAGE_LEVEL_TOPOLOGY,
    LIMIT_SETS_TABULAR_MODIFICATION,
    CREATE_VOLTAGE_LEVEL_SECTION,
    MOVE_VOLTAGE_LEVEL_FEEDER_BAYS
}
