name: Patch

on:
  workflow_dispatch:
    inputs:
      branchRef:
        description: 'Patch branch (format: release-vX.Y.Z)'
        required: true
        type: string

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/backend-libraries/patch-generic.yml@be80e786187595034102a9926ccbedbd1c6661ae
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      branchRef: ${{ github.event.inputs.branchRef }}
    secrets:
      githubappPrivateKey: ${{ secrets.GRIDSUITE_ACTIONS_SECRET }}