name: Release

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type increment (major | minor)'
        required: true
        type: choice
        options:
          - major
          - minor

jobs:
  run-release:
    uses: powsybl/github-ci/.github/workflows/backend-libraries/release-generic.yml@be80e786187595034102a9926ccbedbd1c6661ae
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      versionType: ${{ github.event.inputs.versionType }}
    secrets:
      githubappPrivateKey: ${{ secrets.GRIDSUITE_ACTIONS_SECRET }}